/** @type {import('tailwindcss').Config} config */
const config = {
    content: ['./index.php', './app/**/*.php', './resources/**/*.{php,vue,js}'],
    theme: {
        extend: {
            colors: {}, // Extend Tailwind's default colors
            fontFamily: {
                title: 'arial',
                body: 'arial',
            },
            container: {
                center: true,
                padding: '2rem',
            },
        },
    },
    corePlugins: {
      accentColor : false,
      animation : false,
      aria : false,
      aspectRatio : true,
      backdropBlur : false,
      backdropBrightness : false,
      backdropContrast : false,
      backdropGrayscale : false,
      backdropHueRotate : false,
      backdropInvert : false,
      backdropOpacity : false,
      backdropSaturate : false,
      backdropSepia : false,
      backgroundColor : true,
      backgroundImage : false,
      backgroundOpacity : false,
      backgroundPosition : false,
      backgroundSize : false,
      blur : false,
      borderColor : true,
      borderOpacity : false,
      borderRadius : true,
      borderSpacing : false,
      borderWidth : true,
      boxShadow : true,
      boxShadowColor : true,
      brightness : false,
      caretColor : false,
      colors : true,
      columns : false,
      container : false,
      content : false,
      contrast : false,
      cursor : true,
      divideColor : false,
      divideOpacity : false,
      divideWidth : false,
      dropShadow : true,
      fill : false,
      flex : true,
      flexBasis : false,
      flexGrow : false,
      flexShrink : false,
      fontFamily : true,
      fontSize : true,
      fontWeight : true,
      gap : true,
      gradientColorStops : false,
      gradientColorStopPositions : false,
      grayscale : false,
      gridAutoColumns : false,
      gridAutoRows : false,
      gridColumn : false,
      gridColumnEnd : false,
      gridColumnStart : false,
      gridRow : false,
      gridRowEnd : false,
      gridRowStart : false,
      gridTemplateColumns : false,
      gridTemplateRows : false,
      height : true,
      hueRotate : false,
      inset : true,
      invert : false,
      keyframes : false,
      letterSpacing : false,
      lineClamp : false,
      lineHeight : true,
      listStyleImage : false,
      listStyleType : true,
      margin : true,
      maxHeight : true,
      maxWidth : true,
      minHeight : true,
      minWidth : true,
      objectPosition : false,
      opacity : true,
      order : false,
      outlineColor : false,
      outlineOffset : false,
      outlineWidth : false,
      padding : true,
      placeholderColor : false,
      placeholderOpacity : false,
      ringColor : true,
      ringOffsetColor : true,
      ringOffsetWidth : false,
      ringOpacity : true,
      ringWidth : true,
      rotate : true,
      saturate : false,
      scale : true,
      screens : true,
      scrollMargin : false,
      scrollPadding : false,
      sepia : false,
      skew : false,
      space : true,
      spacing : false,
      stroke : false,
      strokeWidth : false,
      supports : false,
      textColor : true,
      textDecorationColor : false,
      textDecorationThickness : false,
      textIndent : false,
      textOpacity : false,
      textUnderlineOffset : false,
      transformOrigin : false,
      transitionDelay : true,
      transitionDuration : true,
      transitionProperty : true,
      transitionTimingFunction : true,
      translate : true,
      width : true,
      willChange : false,
      zIndex : true,
},
    plugins: [],
};

export default config;
